-- MySQL Script generated by MySQL Workbench
-- Thu Jan  5 11:04:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GasDonLalo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `GasDonLalo` ;

-- -----------------------------------------------------
-- Schema GasDonLalo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GasDonLalo` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema gasdonlalo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gasdonlalo` ;

-- -----------------------------------------------------
-- Schema gasdonlalo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gasdonlalo` DEFAULT CHARACTER SET utf8 ;
USE `GasDonLalo` ;

-- -----------------------------------------------------
-- Table `GasDonLalo`.`departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GasDonLalo`.`departamento` ;

CREATE TABLE IF NOT EXISTS `GasDonLalo`.`departamento` (
  `iddepartamento` INT NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GasDonLalo`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GasDonLalo`.`empleado` ;

CREATE TABLE IF NOT EXISTS `GasDonLalo`.`empleado` (
  `idempleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido_paterno` VARCHAR(30) NOT NULL,
  `apellido_materno` VARCHAR(30) NOT NULL,
  `departamento` INT NOT NULL,
  PRIMARY KEY (`idempleado`),
  INDEX `fk_Empleado_Departamento_idx` (`departamento` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Departamento`
    FOREIGN KEY (`departamento`)
    REFERENCES `GasDonLalo`.`departamento` (`iddepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GasDonLalo`.`monto_faltante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GasDonLalo`.`monto_faltante` ;

CREATE TABLE IF NOT EXISTS `GasDonLalo`.`monto_faltante` (
  `idmonto_faltante` INT NOT NULL AUTO_INCREMENT,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `fecha` DATE NOT NULL,
  `empleado` INT NOT NULL,
  PRIMARY KEY (`idmonto_faltante`),
  INDEX `fk_monto_faltante_Empleado1_idx` (`empleado` ASC) VISIBLE,
  CONSTRAINT `fk_monto_faltante_Empleado1`
    FOREIGN KEY (`empleado`)
    REFERENCES `GasDonLalo`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GasDonLalo`.`incumplimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GasDonLalo`.`incumplimiento` ;

CREATE TABLE IF NOT EXISTS `GasDonLalo`.`incumplimiento` (
  `idincumplimiento` INT NOT NULL AUTO_INCREMENT,
  `incumplimiento` VARCHAR(45) NOT NULL,
  `departamento` INT NOT NULL,
  PRIMARY KEY (`idincumplimiento`),
  INDEX `fk_incumplimiento_departamento1_idx` (`departamento` ASC) VISIBLE,
  CONSTRAINT `fk_incumplimiento_departamento1`
    FOREIGN KEY (`departamento`)
    REFERENCES `GasDonLalo`.`departamento` (`iddepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GasDonLalo`.`formato_salidas_no_conformes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GasDonLalo`.`formato_salidas_no_conformes` ;

CREATE TABLE IF NOT EXISTS `GasDonLalo`.`formato_salidas_no_conformes` (
  `idsalidas_no_conformes` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `descripcion_falla` TEXT NULL,
  `acciones_corregir` TEXT NULL,
  `concesiones` TEXT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `tipo_incumplimiento` INT NOT NULL,
  PRIMARY KEY (`idsalidas_no_conformes`),
  INDEX `fk_formato_salidas_no_conformes_incumplimiento1_idx` (`tipo_incumplimiento` ASC) VISIBLE,
  CONSTRAINT `fk_formato_salidas_no_conformes_incumplimiento1`
    FOREIGN KEY (`tipo_incumplimiento`)
    REFERENCES `GasDonLalo`.`incumplimiento` (`idincumplimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GasDonLalo`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GasDonLalo`.`user` ;

CREATE TABLE IF NOT EXISTS `GasDonLalo`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `empleado` INT NOT NULL,
  INDEX `fk_user_empleado1_idx` (`empleado` ASC) VISIBLE,
  CONSTRAINT `fk_user_empleado1`
    FOREIGN KEY (`empleado`)
    REFERENCES `GasDonLalo`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `GasDonLalo`.`estacion_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GasDonLalo`.`estacion_servicio` ;

CREATE TABLE IF NOT EXISTS `GasDonLalo`.`estacion_servicio` (
  `idestacion_servicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `latitud` DECIMAL(10,6) NULL,
  `longitud` DECIMAL(10,6) NULL,
  `imagen` VARCHAR(45) NULL DEFAULT 'http://localhost:4000/estaciones/gdl1.jpg',
  PRIMARY KEY (`idestacion_servicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GasDonLalo`.`bomba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GasDonLalo`.`bomba` ;

CREATE TABLE IF NOT EXISTS `GasDonLalo`.`bomba` (
  `idbomba` INT NOT NULL,
  `num_bomba` INT NOT NULL,
  `bomba` VARCHAR(45) NULL,
  `estacion_servicio` INT NOT NULL,
  PRIMARY KEY (`idbomba`),
  INDEX `fk_bomba_estacion_servicio1_idx` (`estacion_servicio` ASC) VISIBLE,
  CONSTRAINT `fk_bomba_estacion_servicio1`
    FOREIGN KEY (`estacion_servicio`)
    REFERENCES `GasDonLalo`.`estacion_servicio` (`idestacion_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GasDonLalo`.`checklist_bomba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GasDonLalo`.`checklist_bomba` ;

CREATE TABLE IF NOT EXISTS `GasDonLalo`.`checklist_bomba` (
  `idchecklist_bomba` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `isla_limpia` BIT NULL,
  `aceites_completos` BIT NULL,
  `bomba` INT NULL,
  `turno` ENUM("Mañana", "Tarde", "Noche") NULL,
  `empleado_entrante` INT NULL,
  `empleado_saliente` INT NULL,
  PRIMARY KEY (`idchecklist_bomba`),
  INDEX `fk_check_bomba1_idx` (`bomba` ASC) VISIBLE,
  INDEX `fk_check_empleado1_idx` (`empleado_entrante` ASC) VISIBLE,
  INDEX `fk_check_empleado2_idx` (`empleado_saliente` ASC) VISIBLE,
  CONSTRAINT `fk_check_bomba1`
    FOREIGN KEY (`bomba`)
    REFERENCES `GasDonLalo`.`bomba` (`idbomba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_check_empleado1`
    FOREIGN KEY (`empleado_entrante`)
    REFERENCES `GasDonLalo`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_check_empleado2`
    FOREIGN KEY (`empleado_saliente`)
    REFERENCES `GasDonLalo`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GasDonLalo`.`puntaje_minimo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GasDonLalo`.`puntaje_minimo` ;

CREATE TABLE IF NOT EXISTS `GasDonLalo`.`puntaje_minimo` (
  `idpuntaje_minimo` INT NOT NULL AUTO_INCREMENT,
  `tabla_captura` VARCHAR(20) NOT NULL,
  `puntaje` INT NOT NULL,
  PRIMARY KEY (`idpuntaje_minimo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GasDonLalo`.`mantenimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GasDonLalo`.`mantenimiento` ;

CREATE TABLE IF NOT EXISTS `GasDonLalo`.`mantenimiento` (
  `idmantenimiento` INT NOT NULL AUTO_INCREMENT,
  `mantenimiento` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idmantenimiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GasDonLalo`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GasDonLalo`.`area` ;

CREATE TABLE IF NOT EXISTS `GasDonLalo`.`area` (
  `idarea` INT NOT NULL AUTO_INCREMENT,
  `area` VARCHAR(25) NOT NULL,
  `idmantenimiento` INT NOT NULL,
  PRIMARY KEY (`idarea`),
  INDEX `fk_area_mantenimiento1_idx` (`idmantenimiento` ASC) VISIBLE,
  CONSTRAINT `fk_area_mantenimiento1`
    FOREIGN KEY (`idmantenimiento`)
    REFERENCES `GasDonLalo`.`mantenimiento` (`idmantenimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gasdonlalo`.`estacion_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gasdonlalo`.`estacion_servicio` ;

CREATE TABLE IF NOT EXISTS `gasdonlalo`.`estacion_servicio` (
  `idestacion_servicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `latitud` DECIMAL(10,6) NULL DEFAULT NULL,
  `longitud` DECIMAL(10,6) NULL DEFAULT NULL,
  `imagen` VARCHAR(45) NULL DEFAULT 'http://localhost:4000/estaciones/gdl1.jpg',
  PRIMARY KEY (`idestacion_servicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gasdonlalo`.`departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gasdonlalo`.`departamento` ;

CREATE TABLE IF NOT EXISTS `gasdonlalo`.`departamento` (
  `iddepartamento` INT NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddepartamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gasdonlalo`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gasdonlalo`.`empleado` ;

CREATE TABLE IF NOT EXISTS `gasdonlalo`.`empleado` (
  `idempleado` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido_paterno` VARCHAR(30) NOT NULL,
  `apellido_materno` VARCHAR(30) NOT NULL,
  `iddepartamento` INT NOT NULL,
  `estatus` INT NOT NULL DEFAULT 1,
  `date_baja` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idempleado`),
  INDEX `fk_Empleado_Departamento_idx` (`iddepartamento` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Departamento`
    FOREIGN KEY (`iddepartamento`)
    REFERENCES `gasdonlalo`.`departamento` (`iddepartamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 134
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `GasDonLalo`.`otrabajo_mantenimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GasDonLalo`.`otrabajo_mantenimiento` ;

CREATE TABLE IF NOT EXISTS `GasDonLalo`.`otrabajo_mantenimiento` (
  `idotrabajo_mantenimiento` INT NOT NULL AUTO_INCREMENT,
  `tipo_mantenimiento` ENUM("Correctivo", "Preventivo") NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_termino` DATETIME NOT NULL,
  `descripcion_falla` TEXT NULL,
  `idarea` INT NOT NULL,
  `idestacion_servicio` INT NOT NULL,
  `idempleado_solicita` INT NOT NULL,
  PRIMARY KEY (`idotrabajo_mantenimiento`),
  INDEX `fk_otrabajo_mantenimiento_area1_idx` (`idarea` ASC) VISIBLE,
  INDEX `fk_otrabajo_mantenimiento_estacion_servicio1_idx` (`idestacion_servicio` ASC) VISIBLE,
  INDEX `fk_otrabajo_mantenimiento_empleado1_idx` (`idempleado_solicita` ASC) VISIBLE,
  CONSTRAINT `fk_otrabajo_mantenimiento_area1`
    FOREIGN KEY (`idarea`)
    REFERENCES `GasDonLalo`.`area` (`idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_otrabajo_mantenimiento_estacion_servicio1`
    FOREIGN KEY (`idestacion_servicio`)
    REFERENCES `gasdonlalo`.`estacion_servicio` (`idestacion_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_otrabajo_mantenimiento_empleado1`
    FOREIGN KEY (`idempleado_solicita`)
    REFERENCES `gasdonlalo`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GasDonLalo`.`documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GasDonLalo`.`documento` ;

CREATE TABLE IF NOT EXISTS `GasDonLalo`.`documento` (
  `iddocumento` INT NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`iddocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GasDonLalo`.`control_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GasDonLalo`.`control_documento` ;

CREATE TABLE IF NOT EXISTS `GasDonLalo`.`control_documento` (
  `idcontrol_documento` INT NOT NULL AUTO_INCREMENT,
  `cumple` BIT NOT NULL,
  `idempleado` INT NOT NULL,
  `iddocumento` INT NOT NULL,
  PRIMARY KEY (`idcontrol_documento`),
  INDEX `fk_control_documento_empleado1_idx` (`idempleado` ASC) VISIBLE,
  INDEX `fk_control_documento_documento1_idx` (`iddocumento` ASC) VISIBLE,
  CONSTRAINT `fk_control_documento_empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `gasdonlalo`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_control_documento_documento1`
    FOREIGN KEY (`iddocumento`)
    REFERENCES `GasDonLalo`.`documento` (`iddocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GasDonLalo`.`solicitud_empleo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GasDonLalo`.`solicitud_empleo` ;

CREATE TABLE IF NOT EXISTS `GasDonLalo`.`solicitud_empleo` (
  `idsolicitud_empleo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido_paterno` VARCHAR(30) NOT NULL,
  `apellido_materno` VARCHAR(30) NOT NULL,
  `estatus` ENUM("Contrato", "Practica", "Despido", "Rechazo", "Pendiente") NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `fecha_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idempleado` INT NULL COMMENT 'El id empleado no sera un valor llave, porque esta se rellenara repecto al id que se genere en el checador de entrada/salida y cuando el estatus cambie a practica o contrato, el id se rellenara al idempleado (\"llave de la tabla empleado\") con todos los valores.',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `iddepartamento` INT NOT NULL,
  `motivo` TEXT NULL COMMENT 'Puede ir vacia, solo es valido cuando la solicitud esta rechazada o despido',
  PRIMARY KEY (`idsolicitud_empleo`),
  UNIQUE INDEX `idempleado_UNIQUE` (`idempleado` ASC) VISIBLE,
  INDEX `fk_solicitud_empleo_departamento1_idx` (`iddepartamento` ASC) VISIBLE,
  CONSTRAINT `fk_solicitud_empleo_departamento1`
    FOREIGN KEY (`iddepartamento`)
    REFERENCES `gasdonlalo`.`departamento` (`iddepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GasDonLalo`.`turno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GasDonLalo`.`turno` ;

CREATE TABLE IF NOT EXISTS `GasDonLalo`.`turno` (
  `idturno` INT NOT NULL AUTO_INCREMENT,
  `turno` VARCHAR(6) NOT NULL,
  `hora_empiezo` TIME NOT NULL,
  `hora_termino` TIME NOT NULL,
  `hora_anticipo` TIME NOT NULL,
  PRIMARY KEY (`idturno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GasDonLalo`.`tipo_falta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GasDonLalo`.`tipo_falta` ;

CREATE TABLE IF NOT EXISTS `GasDonLalo`.`tipo_falta` (
  `idtipo_falta` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(30) NOT NULL,
  `descripcion` TEXT NULL COMMENT 'Se le puede añadir una descripcion a la razon de la falta o puede ir vacio si asi lo desean\n',
  `inconforme` BIT NOT NULL DEFAULT 1 COMMENT 'Recibe un valor booleano\ntrue es que la falta que puede generar una inconformidad y false es lo contrario, puede ser una falta justificable y no repercutrir al empleado, el primer dato de esta tabla sera un false por si el empleado capturo en orden',
  PRIMARY KEY (`idtipo_falta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GasDonLalo`.`captura_entrada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GasDonLalo`.`captura_entrada` ;

CREATE TABLE IF NOT EXISTS `GasDonLalo`.`captura_entrada` (
  `idcaptura_entrada` INT NOT NULL AUTO_INCREMENT,
  `hora_entrada` TIME NULL,
  `fecha` DATE NOT NULL,
  `idturno` INT NOT NULL,
  `idtipo_falta` INT NOT NULL COMMENT 'Es caso de que no alla ninguna inconformidad con la entrada, se le asignara siempre el id 1',
  `idempleado` INT NOT NULL,
  PRIMARY KEY (`idcaptura_entrada`),
  INDEX `fk_captura_entrada_turno1_idx` (`idturno` ASC) VISIBLE,
  INDEX `fk_captura_entrada_tipo_falta1_idx` (`idtipo_falta` ASC) VISIBLE,
  INDEX `fk_captura_entrada_empleado1_idx` (`idempleado` ASC) VISIBLE,
  CONSTRAINT `fk_captura_entrada_turno1`
    FOREIGN KEY (`idturno`)
    REFERENCES `GasDonLalo`.`turno` (`idturno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_captura_entrada_tipo_falta1`
    FOREIGN KEY (`idtipo_falta`)
    REFERENCES `GasDonLalo`.`tipo_falta` (`idtipo_falta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_captura_entrada_empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `gasdonlalo`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `gasdonlalo` ;

-- -----------------------------------------------------
-- Table `gasdonlalo`.`bomba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gasdonlalo`.`bomba` ;

CREATE TABLE IF NOT EXISTS `gasdonlalo`.`bomba` (
  `idbomba` INT NOT NULL AUTO_INCREMENT,
  `num_bomba` INT NOT NULL,
  `bomba` VARCHAR(45) NULL DEFAULT NULL,
  `idestacion_servicio` INT NOT NULL,
  PRIMARY KEY (`idbomba`),
  INDEX `fk_bomba_estacion_servicio1_idx` (`idestacion_servicio` ASC) VISIBLE,
  CONSTRAINT `fk_bomba_estacion_servicio1`
    FOREIGN KEY (`idestacion_servicio`)
    REFERENCES `gasdonlalo`.`estacion_servicio` (`idestacion_servicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gasdonlalo`.`checklist_bomba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gasdonlalo`.`checklist_bomba` ;

CREATE TABLE IF NOT EXISTS `gasdonlalo`.`checklist_bomba` (
  `idchecklist_bomba` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `isla_limpia` BIT(1) NOT NULL,
  `aceites_completos` BIT(1) NOT NULL,
  `idbomba` INT NOT NULL,
  `turno` ENUM('Mañana', 'Tarde', 'Noche') NOT NULL,
  `idempleado_entrante` INT NOT NULL,
  `idempleado_saliente` INT NOT NULL,
  `idpuntaje_minimo` INT NOT NULL,
  PRIMARY KEY (`idchecklist_bomba`),
  INDEX `fk_check_bomba1_idx` (`idbomba` ASC) VISIBLE,
  INDEX `fk_check_empleado1_idx` (`idempleado_entrante` ASC) VISIBLE,
  INDEX `fk_check_empleado2_idx` (`idempleado_saliente` ASC) VISIBLE,
  INDEX `fk_checklist_bomba_puntaje_minimo1_idx` (`idpuntaje_minimo` ASC) VISIBLE,
  CONSTRAINT `fk_check_bomba1`
    FOREIGN KEY (`idbomba`)
    REFERENCES `gasdonlalo`.`bomba` (`idbomba`),
  CONSTRAINT `fk_check_empleado1`
    FOREIGN KEY (`idempleado_entrante`)
    REFERENCES `gasdonlalo`.`empleado` (`idempleado`),
  CONSTRAINT `fk_check_empleado2`
    FOREIGN KEY (`idempleado_saliente`)
    REFERENCES `gasdonlalo`.`empleado` (`idempleado`),
  CONSTRAINT `fk_checklist_bomba_puntaje_minimo1`
    FOREIGN KEY (`idpuntaje_minimo`)
    REFERENCES `GasDonLalo`.`puntaje_minimo` (`idpuntaje_minimo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gasdonlalo`.`paso_despachar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gasdonlalo`.`paso_despachar` ;

CREATE TABLE IF NOT EXISTS `gasdonlalo`.`paso_despachar` (
  `idpaso_despachar` INT NOT NULL AUTO_INCREMENT,
  `paso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpaso_despachar`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gasdonlalo`.`evaluacion_despachar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gasdonlalo`.`evaluacion_despachar` ;

CREATE TABLE IF NOT EXISTS `gasdonlalo`.`evaluacion_despachar` (
  `idevaluacion_despachar` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `idempleado` INT NOT NULL,
  `idpaso_despachar` INT NOT NULL,
  `evaluacion` BIT NOT NULL DEFAULT 0,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `identificador` CHAR(34) NOT NULL,
  PRIMARY KEY (`idevaluacion_despachar`),
  INDEX `fk_pasos_para_despachar_empleado1_idx` (`idempleado` ASC) VISIBLE,
  INDEX `fk_evaluacion_para_despachar_pasos_para_despachar1_idx` (`idpaso_despachar` ASC) VISIBLE,
  CONSTRAINT `fk_evaluacion_para_despachar_pasos_para_despachar1`
    FOREIGN KEY (`idpaso_despachar`)
    REFERENCES `gasdonlalo`.`paso_despachar` (`idpaso_despachar`),
  CONSTRAINT `fk_pasos_para_despachar_empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `gasdonlalo`.`empleado` (`idempleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gasdonlalo`.`cumplimiento_uniforme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gasdonlalo`.`cumplimiento_uniforme` ;

CREATE TABLE IF NOT EXISTS `gasdonlalo`.`cumplimiento_uniforme` (
  `idcumplimiento_uniforme` INT NOT NULL AUTO_INCREMENT,
  `cumplimiento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcumplimiento_uniforme`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gasdonlalo`.`evaluacion_uniforme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gasdonlalo`.`evaluacion_uniforme` ;

CREATE TABLE IF NOT EXISTS `gasdonlalo`.`evaluacion_uniforme` (
  `idevaluacion_uniforme` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `idempleado` INT NOT NULL,
  `idcumplimiento_uniforme` INT NOT NULL,
  `idpuntaje_minimo` INT NOT NULL,
  `cumple` BIT NOT NULL,
  `identificador` CHAR(34) NOT NULL,
  PRIMARY KEY (`idevaluacion_uniforme`),
  INDEX `fk_evaluación_de_uniforme_empleado1_idx` (`idempleado` ASC) VISIBLE,
  INDEX `fk_evaluaciones_evaluaciones_de_uniforme1_idx` (`idcumplimiento_uniforme` ASC) VISIBLE,
  INDEX `fk_evaluacion_uniforme_puntaje_minimo1_idx` (`idpuntaje_minimo` ASC) VISIBLE,
  CONSTRAINT `fk_evaluaciones_evaluaciones_de_uniforme1`
    FOREIGN KEY (`idcumplimiento_uniforme`)
    REFERENCES `gasdonlalo`.`cumplimiento_uniforme` (`idcumplimiento_uniforme`),
  CONSTRAINT `fk_evaluación_de_uniforme_empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `gasdonlalo`.`empleado` (`idempleado`),
  CONSTRAINT `fk_evaluacion_uniforme_puntaje_minimo1`
    FOREIGN KEY (`idpuntaje_minimo`)
    REFERENCES `GasDonLalo`.`puntaje_minimo` (`idpuntaje_minimo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gasdonlalo`.`incumplimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gasdonlalo`.`incumplimiento` ;

CREATE TABLE IF NOT EXISTS `gasdonlalo`.`incumplimiento` (
  `idincumplimiento` INT NOT NULL AUTO_INCREMENT,
  `incumplimiento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idincumplimiento`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gasdonlalo`.`salida_noconforme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gasdonlalo`.`salida_noconforme` ;

CREATE TABLE IF NOT EXISTS `gasdonlalo`.`salida_noconforme` (
  `idsalida_noconforme` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `descripcion_falla` TEXT NULL DEFAULT NULL,
  `acciones_corregir` TEXT NULL DEFAULT NULL,
  `concesiones` TEXT NULL DEFAULT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `idempleado` INT NOT NULL,
  `idempleado_autoriza` INT NOT NULL,
  `idincumplimiento` INT NOT NULL,
  PRIMARY KEY (`idsalida_noconforme`),
  INDEX `fk_formato_salidas_no_conformes_empleado1_idx` (`idempleado` ASC) VISIBLE,
  INDEX `fk_formato_salidas_no_conformes_empleado2_idx` (`idempleado_autoriza` ASC) VISIBLE,
  INDEX `fk_salida_noconforme_incumplimiento1_idx` (`idincumplimiento` ASC) VISIBLE,
  CONSTRAINT `fk_formato_salidas_no_conformes_empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `gasdonlalo`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formato_salidas_no_conformes_empleado2`
    FOREIGN KEY (`idempleado_autoriza`)
    REFERENCES `gasdonlalo`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_salida_noconforme_incumplimiento1`
    FOREIGN KEY (`idincumplimiento`)
    REFERENCES `gasdonlalo`.`incumplimiento` (`idincumplimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gasdonlalo`.`recurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gasdonlalo`.`recurso` ;

CREATE TABLE IF NOT EXISTS `gasdonlalo`.`recurso` (
  `idrecurso` INT NOT NULL AUTO_INCREMENT,
  `recurso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrecurso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gasdonlalo`.`monto_faltante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gasdonlalo`.`monto_faltante` ;

CREATE TABLE IF NOT EXISTS `gasdonlalo`.`monto_faltante` (
  `idmonto_faltante` INT NOT NULL AUTO_INCREMENT,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `fecha` DATE NOT NULL,
  `idempleado` INT NOT NULL,
  PRIMARY KEY (`idmonto_faltante`),
  INDEX `fk_monto_faltante_Empleado1_idx` (`idempleado` ASC) VISIBLE,
  CONSTRAINT `fk_monto_faltante_Empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `gasdonlalo`.`empleado` (`idempleado`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gasdonlalo`.`recoleccion_efectivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gasdonlalo`.`recoleccion_efectivo` ;

CREATE TABLE IF NOT EXISTS `gasdonlalo`.`recoleccion_efectivo` (
  `idrecoleccion_efectivo` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `idempleado` INT NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idrecoleccion_efectivo`),
  INDEX `fk_recoleccion_de_efectivo_empleado1_idx` (`idempleado` ASC) VISIBLE,
  CONSTRAINT `fk_recoleccion_de_efectivo_empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `gasdonlalo`.`empleado` (`idempleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gasdonlalo`.`recurso_despachador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gasdonlalo`.`recurso_despachador` ;

CREATE TABLE IF NOT EXISTS `gasdonlalo`.`recurso_despachador` (
  `idrecurso_despachador` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `idempleado` INT NOT NULL,
  `idrecurso` INT NOT NULL,
  `idrecurso_minimo` INT NOT NULL,
  `evaluacion` BIT NOT NULL DEFAULT 0,
  `identificador` CHAR(34) NOT NULL,
  PRIMARY KEY (`idrecurso_despachador`),
  INDEX `fk_recursos_de_despachador_empleado1_idx` (`idempleado` ASC) VISIBLE,
  INDEX `fk_recursos_de_despachador_lista_de_recursos1_idx` (`idrecurso` ASC) VISIBLE,
  INDEX `fk_recursos_de_despachador_puntaje_minimo1_idx` (`idrecurso_minimo` ASC) VISIBLE,
  CONSTRAINT `fk_recursos_de_despachador_empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `gasdonlalo`.`empleado` (`idempleado`),
  CONSTRAINT `fk_recursos_de_despachador_lista_de_recursos1`
    FOREIGN KEY (`idrecurso`)
    REFERENCES `gasdonlalo`.`recurso` (`idrecurso`),
  CONSTRAINT `fk_recursos_de_despachador_puntaje_minimo1`
    FOREIGN KEY (`idrecurso_minimo`)
    REFERENCES `GasDonLalo`.`puntaje_minimo` (`idpuntaje_minimo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gasdonlalo`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gasdonlalo`.`user` ;

CREATE TABLE IF NOT EXISTS `gasdonlalo`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idempleado` INT NOT NULL,
  INDEX `fk_user_empleado1_idx` (`idempleado` ASC) VISIBLE,
  CONSTRAINT `fk_user_empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `gasdonlalo`.`empleado` (`idempleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gasdonlalo`.`turno_estacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gasdonlalo`.`turno_estacion` ;

CREATE TABLE IF NOT EXISTS `gasdonlalo`.`turno_estacion` (
  `idestacion_servicio` INT NOT NULL,
  `idturno` INT NOT NULL,
  PRIMARY KEY (`idestacion_servicio`, `idturno`),
  INDEX `fk_estacion_servicio_has_turno_turno1_idx` (`idturno` ASC) VISIBLE,
  INDEX `fk_estacion_servicio_has_turno_estacion_servicio1_idx` (`idestacion_servicio` ASC) VISIBLE,
  CONSTRAINT `fk_estacion_servicio_has_turno_estacion_servicio1`
    FOREIGN KEY (`idestacion_servicio`)
    REFERENCES `gasdonlalo`.`estacion_servicio` (`idestacion_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estacion_servicio_has_turno_turno1`
    FOREIGN KEY (`idturno`)
    REFERENCES `GasDonLalo`.`turno` (`idturno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
