-- MySQL Script generated by MySQL Workbench
-- mié 23 ago 2023 09:57:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GasDonLalo
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gasdonlalo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `departamento` ;

CREATE TABLE IF NOT EXISTS `departamento` (
  `iddepartamento` INT NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empleado` ;

CREATE TABLE IF NOT EXISTS `empleado` (
  `idempleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido_paterno` VARCHAR(30) NOT NULL,
  `apellido_materno` VARCHAR(30) NOT NULL,
  `departamento` INT NOT NULL,
  PRIMARY KEY (`idempleado`),
  INDEX `fk_Empleado_Departamento_idx` (`departamento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monto_faltante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monto_faltante` ;

CREATE TABLE IF NOT EXISTS `monto_faltante` (
  `idmonto_faltante` INT NOT NULL AUTO_INCREMENT,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `fecha` DATE NOT NULL,
  `empleado` INT NOT NULL,
  PRIMARY KEY (`idmonto_faltante`),
  INDEX `fk_monto_faltante_Empleado1_idx` (`empleado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incumplimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `incumplimiento` ;

CREATE TABLE IF NOT EXISTS `incumplimiento` (
  `idincumplimiento` INT NOT NULL AUTO_INCREMENT,
  `incumplimiento` VARCHAR(45) NOT NULL,
  `departamento` INT NOT NULL,
  PRIMARY KEY (`idincumplimiento`),
  INDEX `fk_incumplimiento_departamento1_idx` (`departamento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formato_salidas_no_conformes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formato_salidas_no_conformes` ;

CREATE TABLE IF NOT EXISTS `formato_salidas_no_conformes` (
  `idsalidas_no_conformes` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `descripcion_falla` TEXT NULL,
  `acciones_corregir` TEXT NULL,
  `concesiones` TEXT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `tipo_incumplimiento` INT NOT NULL,
  PRIMARY KEY (`idsalidas_no_conformes`),
  INDEX `fk_formato_salidas_no_conformes_incumplimiento1_idx` (`tipo_incumplimiento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacion_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estacion_servicio` ;

CREATE TABLE IF NOT EXISTS `estacion_servicio` (
  `idestacion_servicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `latitud` DECIMAL(10,6) NULL,
  `longitud` DECIMAL(10,6) NULL,
  `imagen` VARCHAR(45) NULL DEFAULT 'http://localhost:4000/estaciones/gdl1.jpg',
  PRIMARY KEY (`idestacion_servicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bomba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bomba` ;

CREATE TABLE IF NOT EXISTS `bomba` (
  `idbomba` INT NOT NULL,
  `num_bomba` INT NOT NULL,
  `bomba` VARCHAR(45) NULL,
  `estacion_servicio` INT NOT NULL,
  PRIMARY KEY (`idbomba`),
  INDEX `fk_bomba_estacion_servicio1_idx` (`estacion_servicio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `checklist_bomba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checklist_bomba` ;

CREATE TABLE IF NOT EXISTS `checklist_bomba` (
  `idchecklist_bomba` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `isla_limpia` BIT NULL,
  `aceites_completos` BIT NULL,
  `bomba` INT NULL,
  `turno` ENUM("Mañana", "Tarde", "Noche") NULL,
  `empleado_entrante` INT NULL,
  `empleado_saliente` INT NULL,
  PRIMARY KEY (`idchecklist_bomba`),
  INDEX `fk_check_bomba1_idx` (`bomba` ASC) VISIBLE,
  INDEX `fk_check_empleado1_idx` (`empleado_entrante` ASC) VISIBLE,
  INDEX `fk_check_empleado2_idx` (`empleado_saliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puntaje_minimo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `puntaje_minimo` ;

CREATE TABLE IF NOT EXISTS `puntaje_minimo` (
  `idpuntaje_minimo` INT NOT NULL AUTO_INCREMENT,
  `tabla_captura` VARCHAR(20) NOT NULL,
  `puntaje` INT NOT NULL,
  PRIMARY KEY (`idpuntaje_minimo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimiento` ;

CREATE TABLE IF NOT EXISTS `mantenimiento` (
  `idmantenimiento` INT NOT NULL AUTO_INCREMENT,
  `mantenimiento` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idmantenimiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `area` ;

CREATE TABLE IF NOT EXISTS `area` (
  `idarea` INT NOT NULL AUTO_INCREMENT,
  `area` VARCHAR(25) NOT NULL,
  `idmantenimiento` INT NOT NULL,
  PRIMARY KEY (`idarea`),
  INDEX `fk_area_mantenimiento1_idx` (`idmantenimiento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacion_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estacion_servicio` ;

CREATE TABLE IF NOT EXISTS `estacion_servicio` (
  `idestacion_servicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `latitud` DECIMAL(10,6) NULL DEFAULT NULL,
  `longitud` DECIMAL(10,6) NULL DEFAULT NULL,
  `imagen` VARCHAR(45) NULL DEFAULT 'http://localhost:4000/estaciones/gdl1.jpg',
  PRIMARY KEY (`idestacion_servicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `departamento` ;

CREATE TABLE IF NOT EXISTS `departamento` (
  `iddepartamento` INT NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddepartamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empleado` ;

CREATE TABLE IF NOT EXISTS `empleado` (
  `idempleado` INT NOT NULL AUTO_INCREMENT,
  `idchecador` INT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido_paterno` VARCHAR(30) NOT NULL,
  `apellido_materno` VARCHAR(30) NOT NULL,
  `iddepartamento` INT NOT NULL,
  `estatus` ENUM("Contrato", "Practica", "Despido", "Rechazado", "Pendiente") NOT NULL COMMENT 'Contrato, Practica, Despido, Rehazo, Pendiente',
  `edad` INT NULL,
  `date_baja` DATE NULL DEFAULT NULL,
  `fecha_registro` DATETIME NOT NULL,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `motivo` TEXT NULL,
  `color` VARCHAR(25) NULL,
  PRIMARY KEY (`idempleado`),
  INDEX `fk_Empleado_Departamento_idx` (`iddepartamento` ASC) VISIBLE,
  UNIQUE INDEX `idchecador_UNIQUE` (`idchecador` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 134
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `otrabajo_mantenimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otrabajo_mantenimiento` ;

CREATE TABLE IF NOT EXISTS `otrabajo_mantenimiento` (
  `idotrabajo_mantenimiento` INT NOT NULL AUTO_INCREMENT,
  `tipo_mantenimiento` ENUM("Correctivo", "Preventivo") NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_termino` DATETIME NOT NULL,
  `descripcion_falla` TEXT NULL,
  `idarea` INT NOT NULL,
  `idestacion_servicio` INT NOT NULL,
  `idempleado_solicita` INT NOT NULL,
  PRIMARY KEY (`idotrabajo_mantenimiento`),
  INDEX `fk_otrabajo_mantenimiento_area1_idx` (`idarea` ASC) VISIBLE,
  INDEX `fk_otrabajo_mantenimiento_estacion_servicio1_idx` (`idestacion_servicio` ASC) VISIBLE,
  INDEX `fk_otrabajo_mantenimiento_empleado1_idx` (`idempleado_solicita` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `documento` ;

CREATE TABLE IF NOT EXISTS `documento` (
  `iddocumento` INT NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`iddocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `control_documento` ;

CREATE TABLE IF NOT EXISTS `control_documento` (
  `idcontrol_documento` INT NOT NULL AUTO_INCREMENT,
  `cumple` BIT NOT NULL,
  `idempleado` INT NOT NULL,
  `iddocumento` INT NOT NULL,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idcontrol_documento`),
  INDEX `fk_control_documento_empleado1_idx` (`idempleado` ASC) VISIBLE,
  INDEX `fk_control_documento_documento1_idx` (`iddocumento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `turno` ;

CREATE TABLE IF NOT EXISTS `turno` (
  `idturno` INT NOT NULL AUTO_INCREMENT,
  `turno` VARCHAR(6) NOT NULL,
  `hora_empiezo` TIME NOT NULL,
  `hora_termino` TIME NOT NULL,
  `hora_anticipo` TIME NOT NULL,
  `mostrar` BIT NOT NULL,
  PRIMARY KEY (`idturno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipo_falta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipo_falta` ;

CREATE TABLE IF NOT EXISTS `tipo_falta` (
  `idtipo_falta` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(30) NOT NULL,
  `descripcion` TEXT NULL COMMENT 'Se le puede añadir una descripcion a la razon de la falta o puede ir vacio si asi lo desean\n',
  `color` VARCHAR(31) NOT NULL DEFAULT 'rgba(255, 255, 0, 1)',
  PRIMARY KEY (`idtipo_falta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captura_entrada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `captura_entrada` ;

CREATE TABLE IF NOT EXISTS `captura_entrada` (
  `idcaptura_entrada` INT NOT NULL AUTO_INCREMENT,
  `hora_entrada` TIME NULL,
  `fecha` DATE NOT NULL,
  `idtipo_falta` INT NULL COMMENT 'Es caso de que no alla ninguna inconformidad con la entrada, se le asignara siempre el id 1',
  `idempleado` INT NOT NULL,
  `minutos_retardos` VARCHAR(10) NULL,
  `hora_establecida` TIME NULL,
  PRIMARY KEY (`idcaptura_entrada`),
  INDEX `fk_captura_entrada_tipo_falta1_idx` (`idtipo_falta` ASC) VISIBLE,
  INDEX `fk_captura_entrada_empleado1_idx` (`idempleado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venta_litros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `venta_litros` ;

CREATE TABLE IF NOT EXISTS `venta_litros` (
  `idventa_litros` INT NOT NULL AUTO_INCREMENT,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `fecha` DATE NOT NULL,
  `idempleado` INT NOT NULL,
  `idestacion_servicio` INT NOT NULL,
  `descalificado` BIT NULL DEFAULT 0,
  PRIMARY KEY (`idventa_litros`),
  INDEX `fk_venta_litros_empleado1_idx` (`idempleado` ASC) VISIBLE,
  INDEX `fk_venta_litros_estacion_servicio1_idx` (`idestacion_servicio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venta_aceite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `venta_aceite` ;

CREATE TABLE IF NOT EXISTS `venta_aceite` (
  `idventa_aceite` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `idempleado` INT NOT NULL,
  `idestacion_servicio` INT NOT NULL,
  `descalificado` BIT NULL DEFAULT 0,
  PRIMARY KEY (`idventa_aceite`),
  INDEX `fk_venta_aceite_empleado1_idx` (`idempleado` ASC) VISIBLE,
  INDEX `fk_venta_aceite_estacion_servicio1_idx` (`idestacion_servicio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recurso_entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recurso_entrega` ;

CREATE TABLE IF NOT EXISTS `recurso_entrega` (
  `idrecurso_entrega` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `cantidad` INT NOT NULL,
  `recurso` TEXT NOT NULL,
  `idempleado_recibe` INT NOT NULL,
  `tipo_recibo` ENUM("Entrega", "Devolución", "A cambio") NOT NULL,
  `estado` ENUM("Nuevo", "Usado") NOT NULL,
  PRIMARY KEY (`idrecurso_entrega`),
  INDEX `fk_recurso_entrega_empleado1_idx` (`idempleado_recibe` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concurso` ;

CREATE TABLE IF NOT EXISTS `concurso` (
  `idconcurso` INT NOT NULL AUTO_INCREMENT,
  `concurso` INT NOT NULL COMMENT 'El primero es de madrugador, el segundo de octanoso y el tercero de aceitoso, los demas pueden provenir del usuario.',
  `iddepartamento` INT NOT NULL,
  PRIMARY KEY (`idconcurso`),
  INDEX `fk_concurso_departamento1_idx` (`iddepartamento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incumplimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `incumplimiento` ;

CREATE TABLE IF NOT EXISTS `incumplimiento` (
  `idincumplimiento` INT NOT NULL AUTO_INCREMENT,
  `incumplimiento` VARCHAR(45) NOT NULL,
  `departamento` INT NULL,
  PRIMARY KEY (`idincumplimiento`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `categorizar_incumplimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categorizar_incumplimiento` ;

CREATE TABLE IF NOT EXISTS `categorizar_incumplimiento` (
  `idconcurso` INT NOT NULL,
  `idincumplimiento` INT NOT NULL,
  `cantidad` INT NULL DEFAULT 1,
  PRIMARY KEY (`idconcurso`, `idincumplimiento`),
  INDEX `fk_concurso_has_incumplimiento_incumplimiento1_idx` (`idincumplimiento` ASC) VISIBLE,
  INDEX `fk_concurso_has_incumplimiento_concurso1_idx` (`idconcurso` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `area_trabajo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `area_trabajo` ;

CREATE TABLE IF NOT EXISTS `area_trabajo` (
  `idarea_trabajo` INT NOT NULL AUTO_INCREMENT,
  `area` VARCHAR(45) NOT NULL COMMENT 'Son las opciones que se mostraran en la interfaz principal del programa',
  PRIMARY KEY (`idarea_trabajo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `permiso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `permiso` ;

CREATE TABLE IF NOT EXISTS `permiso` (
  `idpermiso` INT NOT NULL,
  `permiso` VARCHAR(45) NOT NULL,
  `peticion` VARCHAR(20) NOT NULL,
  `idarea_trabajo` INT NOT NULL,
  `descripcion` TEXT NULL,
  PRIMARY KEY (`idpermiso`),
  INDEX `fk_permiso_area_trabajo1_idx` (`idarea_trabajo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sncacumuladas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sncacumuladas` ;

CREATE TABLE IF NOT EXISTS `sncacumuladas` (
  `idsncacumuladas` INT NOT NULL AUTO_INCREMENT,
  `idincumplimiento` INT NOT NULL,
  `capturado` BIT NOT NULL DEFAULT 0,
  `idempleado` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idsncacumuladas`),
  INDEX `fk_sncacumuladas_incumplimiento1_idx` (`idincumplimiento` ASC) VISIBLE,
  INDEX `fk_sncacumuladas_empleado1_idx` (`idempleado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gas` ;

CREATE TABLE IF NOT EXISTS `gas` (
  `idgas` CHAR NOT NULL COMMENT 'El gas son las galonias Magna, Disiel y Premiun y el id es la primera letra de cada palabra',
  `nombre` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`idgas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `precios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `precios` ;

CREATE TABLE IF NOT EXISTS `precios` (
  `idprecio` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `idgas` CHAR NOT NULL,
  `updatedAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `idempleado_captura` INT NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idprecio`),
  INDEX `fk_precios_gas1_idx` (`idgas` ASC) VISIBLE,
  INDEX `fk_precios_empleado1_idx` (`idempleado_captura` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oyl_cumplimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oyl_cumplimiento` ;

CREATE TABLE IF NOT EXISTS `oyl_cumplimiento` (
  `idoyl_cumplimiento` INT NOT NULL AUTO_INCREMENT,
  `cumplimiento` VARCHAR(45) NOT NULL COMMENT 'El nombre del incumplimiento',
  `descripcion` VARCHAR(45) NOT NULL COMMENT 'La descripción que se le dara, se mostrara dentro de ( ) y se mostrara en la misma celda del cumplimiento\n',
  `parte` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idoyl_cumplimiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oyl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oyl` ;

CREATE TABLE IF NOT EXISTS `oyl` (
  `idoyl` INT NOT NULL AUTO_INCREMENT COMMENT 'Tabla que se relaciona con las islas de orden y limpieza',
  `fecha` DATE NOT NULL,
  `isla` INT NOT NULL,
  `idestacion_servicio` INT NOT NULL,
  `idempleado` INT NOT NULL,
  `idoyl_cumplimiento` INT NOT NULL,
  `idturno` INT NOT NULL,
  `identificador` CHAR(34) NOT NULL,
  `cumple` BIT NOT NULL,
  `incidentes` TEXT NULL COMMENT 'Po si ocurre algun incidente durante la evaluación',
  PRIMARY KEY (`idoyl`),
  INDEX `fk_oyl_estacion_servicio1_idx` (`idestacion_servicio` ASC) VISIBLE,
  INDEX `fk_oyl_empleado1_idx` (`idempleado` ASC) VISIBLE,
  INDEX `fk_oyl_oyl_cumplimiento1_idx` (`idoyl_cumplimiento` ASC) VISIBLE,
  INDEX `fk_oyl_turno1_idx` (`idturno` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `islas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `islas` ;

CREATE TABLE IF NOT EXISTS `islas` (
  `idisla` INT NOT NULL AUTO_INCREMENT,
  `nisla` INT NOT NULL,
  `idestacion_servicio` INT NOT NULL,
  `habilitada` BIT NOT NULL,
  PRIMARY KEY (`idisla`),
  INDEX `fk_islas_estacion_servicio1_idx` (`idestacion_servicio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mangueras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mangueras` ;

CREATE TABLE IF NOT EXISTS `mangueras` (
  `idmanguera` VARCHAR(3) NOT NULL,
  `tiene` BIT NOT NULL DEFAULT 1,
  `idisla` INT NOT NULL,
  `idgas` CHAR NOT NULL,
  `direccion` ENUM("iz", "dr") NOT NULL,
  PRIMARY KEY (`idmanguera`, `idisla`, `idgas`, `direccion`),
  INDEX `fk_islas_has_gas_gas1_idx` (`idgas` ASC) VISIBLE,
  INDEX `fk_islas_has_gas_islas1_idx` (`idisla` ASC) VISIBLE,
  UNIQUE INDEX `idmanguera_UNIQUE` (`idmanguera` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auditorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auditorias` ;

CREATE TABLE IF NOT EXISTS `auditorias` (
  `idauditoria` INT NOT NULL AUTO_INCREMENT,
  `peticion` VARCHAR(45) NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `idempleado` INT NOT NULL,
  `accion` ENUM("GET", "POST", "PUT", "DELETE") NOT NULL,
  `idaffectado` VARCHAR(255) NULL,
  PRIMARY KEY (`idauditoria`),
  INDEX `fk_auditorias_empleado1_idx` (`idempleado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios` ;

CREATE TABLE IF NOT EXISTS `horarios` (
  `idhorario` INT NOT NULL AUTO_INCREMENT,
  `idempleado` INT NOT NULL,
  `idturno` INT NOT NULL,
  `fechaturno` DATE NOT NULL,
  `fechaliquidacion` DATE NOT NULL,
  `idestacion_servicio` INT NOT NULL,
  PRIMARY KEY (`idhorario`),
  INDEX `fk_horarios_turno1_idx` (`idturno` ASC) VISIBLE,
  INDEX `fk_horarios_empleado1_idx` (`idempleado` ASC) VISIBLE,
  INDEX `fk_horarios_estacion_servicio1_idx` (`idestacion_servicio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `liquidaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `liquidaciones` ;

CREATE TABLE IF NOT EXISTS `liquidaciones` (
  `idliquidacion` INT NOT NULL AUTO_INCREMENT,
  `lecturas` JSON NULL,
  `idislas` JSON NOT NULL,
  `paginacion` JSON NULL,
  `cancelado` TEXT NULL,
  `fechaCancelado` DATE NULL,
  `capturado` BIT NOT NULL DEFAULT 0,
  `idempleado_captura` INT NULL,
  `idhorario` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `num_impresiones` INT NOT NULL,
  PRIMARY KEY (`idliquidacion`),
  INDEX `fk_liquidaciones_empleado1_idx` (`idempleado_captura` ASC) VISIBLE,
  INDEX `fk_liquidaciones_horarios1_idx` (`idhorario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codigos_uso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codigos_uso` ;

CREATE TABLE IF NOT EXISTS `codigos_uso` (
  `idcodigo_uso` CHAR(2) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`idcodigo_uso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vales` ;

CREATE TABLE IF NOT EXISTS `vales` (
  `idvale` INT NOT NULL AUTO_INCREMENT COMMENT '	',
  `monto` DECIMAL(19,2) NOT NULL,
  `combustible` CHAR NOT NULL,
  `idliquidacion` INT NOT NULL,
  `folio` INT NULL,
  `label` VARCHAR(8) NOT NULL,
  `idcodigos_uso` CHAR(2) NOT NULL,
  PRIMARY KEY (`idvale`),
  INDEX `fk_vales_gas1_idx` (`combustible` ASC) VISIBLE,
  INDEX `fk_vales_liquidaciones1_idx` (`idliquidacion` ASC) VISIBLE,
  INDEX `fk_vales_codigos_uso1_idx` (`idcodigos_uso` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `efectivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `efectivo` ;

CREATE TABLE IF NOT EXISTS `efectivo` (
  `idefectivo` INT NOT NULL AUTO_INCREMENT,
  `monto` DECIMAL(19,2) NOT NULL,
  `idliquidacion` INT NOT NULL,
  `folio` VARCHAR(45) NULL,
  `codigos_uso` CHAR(2) NOT NULL,
  PRIMARY KEY (`idefectivo`),
  INDEX `fk_efectivo_liquidaciones1_idx` (`idliquidacion` ASC) VISIBLE,
  INDEX `fk_efectivo_codigos_uso1_idx` (`codigos_uso` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipos_nominas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipos_nominas` ;

CREATE TABLE IF NOT EXISTS `tipos_nominas` (
  `idtipo_nomina` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `banco` VARCHAR(20) NULL,
  PRIMARY KEY (`idtipo_nomina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `detalles` ;

CREATE TABLE IF NOT EXISTS `detalles` (
  `idempleado` INT NOT NULL,
  `idtipo_nomina` INT NOT NULL,
  INDEX `fk_nomina_empleado_empleado1_idx` (`idempleado` ASC) VISIBLE,
  INDEX `fk_nomina_empleado_tipos_nominas1_idx` (`idtipo_nomina` ASC) VISIBLE,
  PRIMARY KEY (`idempleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `info_lecturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `info_lecturas` ;

CREATE TABLE IF NOT EXISTS `info_lecturas` (
  `idinfo_lectura` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `idliquidacion` INT NOT NULL,
  `idestacion_servicio` INT NOT NULL,
  `cancelado` BIT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idinfo_lectura`),
  INDEX `fk_info_lecturas_liquidaciones1_idx` (`idliquidacion` ASC) VISIBLE,
  INDEX `fk_info_lecturas_estacion_servicio1_idx` (`idestacion_servicio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lecturas_finales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lecturas_finales` ;

CREATE TABLE IF NOT EXISTS `lecturas_finales` (
  `idmanguera` VARCHAR(3) NOT NULL,
  `idinfo_lectura` INT NOT NULL,
  `lecturaI` INT NOT NULL,
  `lecturaF` INT NOT NULL,
  `precio` DECIMAL(19,2) NOT NULL,
  `importe` DECIMAL(19,2) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  PRIMARY KEY (`idmanguera`, `idinfo_lectura`),
  INDEX `fk_info_lecturas_has_mangueras_mangueras1_idx` (`idmanguera` ASC) VISIBLE,
  INDEX `fk_info_lecturas_has_mangueras_info_lecturas1_idx` (`idinfo_lectura` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `llaves_acceso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `llaves_acceso` ;

CREATE TABLE IF NOT EXISTS `llaves_acceso` (
  `idempleado` INT NOT NULL,
  `key` CHAR(10) NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `createdAt` DATETIME NOT NULL,
  INDEX `fk_llaves_acceso_empleado1_idx` (`idempleado` ASC) VISIBLE,
  UNIQUE INDEX `key_UNIQUE` (`key` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `efectivo_tienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `efectivo_tienda` ;

CREATE TABLE IF NOT EXISTS `efectivo_tienda` (
  `idefectivo` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `monto` DECIMAL(19,2) NOT NULL,
  `idcodigo_uso` CHAR(2) NOT NULL,
  `folio` VARCHAR(45) NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`idefectivo`),
  INDEX `fk_efectivo_tienda_codigos_uso1_idx` (`idcodigo_uso` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control_volumetrico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `control_volumetrico` ;

CREATE TABLE IF NOT EXISTS `control_volumetrico` (
  `idcontrol_volumetrico` INT NOT NULL AUTO_INCREMENT,
  `litros` DECIMAL(19,2) NOT NULL,
  `fecha` DATE NOT NULL,
  `idestacion_servicio` INT NOT NULL,
  PRIMARY KEY (`idcontrol_volumetrico`),
  INDEX `fk_control_volumetrico_estacion_servicio1_idx` (`idestacion_servicio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `preliquidaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `preliquidaciones` ;

CREATE TABLE IF NOT EXISTS `preliquidaciones` (
  `idpreliquidacion` INT NOT NULL AUTO_INCREMENT,
  `lecturas` JSON NOT NULL,
  `vales` JSON NOT NULL,
  `efectivo` JSON NOT NULL,
  `idempleado` INT NOT NULL,
  `idturno` INT NOT NULL,
  `fechaturno` DATE NOT NULL,
  `idestacion_servicio` INT NOT NULL,
  `createdAt` DATE NOT NULL,
  `updatedAt` DATE NOT NULL,
  PRIMARY KEY (`idpreliquidacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bomba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bomba` ;

CREATE TABLE IF NOT EXISTS `bomba` (
  `idbomba` INT NOT NULL AUTO_INCREMENT,
  `num_bomba` INT NOT NULL,
  `bomba` VARCHAR(45) NULL DEFAULT NULL,
  `idestacion_servicio` INT NOT NULL,
  PRIMARY KEY (`idbomba`),
  INDEX `fk_bomba_estacion_servicio1_idx` (`idestacion_servicio` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `checklist_bomba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checklist_bomba` ;

CREATE TABLE IF NOT EXISTS `checklist_bomba` (
  `idchecklist_bomba` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `isla_limpia` BIT(1) NOT NULL,
  `aceites_completos` BIT(1) NOT NULL,
  `turno` BIT NOT NULL,
  `bomba` BIT NOT NULL,
  `estacion_servicio` BIT NOT NULL,
  `idempleado` INT NOT NULL,
  `empleado_entrante` BIT NOT NULL,
  `idempleado_saliente` INT NOT NULL,
  `fechac` BIT NOT NULL,
  `empleado_saliente` BIT NOT NULL,
  `incidentes` TEXT NULL,
  PRIMARY KEY (`idchecklist_bomba`),
  INDEX `fk_check_empleado1_idx` (`idempleado` ASC) VISIBLE,
  INDEX `fk_checklist_bomba_empleado1_idx` (`idempleado_saliente` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `paso_despachar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paso_despachar` ;

CREATE TABLE IF NOT EXISTS `paso_despachar` (
  `idpaso_despachar` INT NOT NULL AUTO_INCREMENT,
  `paso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpaso_despachar`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `evaluacion_despachar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `evaluacion_despachar` ;

CREATE TABLE IF NOT EXISTS `evaluacion_despachar` (
  `idevaluacion_despachar` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `idempleado` INT NOT NULL,
  `idpaso_despachar` INT NOT NULL,
  `evaluacion` BIT NOT NULL DEFAULT 0,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `identificador` CHAR(34) NOT NULL,
  PRIMARY KEY (`idevaluacion_despachar`),
  INDEX `fk_pasos_para_despachar_empleado1_idx` (`idempleado` ASC) VISIBLE,
  INDEX `fk_evaluacion_para_despachar_pasos_para_despachar1_idx` (`idpaso_despachar` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cumplimiento_uniforme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cumplimiento_uniforme` ;

CREATE TABLE IF NOT EXISTS `cumplimiento_uniforme` (
  `idcumplimiento_uniforme` INT NOT NULL AUTO_INCREMENT,
  `cumplimiento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcumplimiento_uniforme`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `evaluacion_uniforme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `evaluacion_uniforme` ;

CREATE TABLE IF NOT EXISTS `evaluacion_uniforme` (
  `idevaluacion_uniforme` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `idempleado` INT NOT NULL,
  `idcumplimiento_uniforme` INT NOT NULL,
  `idpuntaje_minimo` INT NOT NULL,
  `cumple` BIT NOT NULL,
  `identificador` CHAR(34) NOT NULL,
  PRIMARY KEY (`idevaluacion_uniforme`),
  INDEX `fk_evaluación_de_uniforme_empleado1_idx` (`idempleado` ASC) VISIBLE,
  INDEX `fk_evaluaciones_evaluaciones_de_uniforme1_idx` (`idcumplimiento_uniforme` ASC) VISIBLE,
  INDEX `fk_evaluacion_uniforme_puntaje_minimo1_idx` (`idpuntaje_minimo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `salida_noconforme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `salida_noconforme` ;

CREATE TABLE IF NOT EXISTS `salida_noconforme` (
  `idsalida_noconforme` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `descripcion_falla` TEXT NOT NULL,
  `acciones_corregir` TEXT NULL DEFAULT NULL,
  `concesiones` TEXT NULL DEFAULT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `idempleado` INT NOT NULL,
  `idincumplimiento` INT NOT NULL,
  `idempleado_autoriza` INT NOT NULL,
  PRIMARY KEY (`idsalida_noconforme`),
  INDEX `fk_formato_salidas_no_conformes_empleado1_idx` (`idempleado` ASC) VISIBLE,
  INDEX `fk_salida_noconforme_incumplimiento1_idx` (`idincumplimiento` ASC) VISIBLE,
  INDEX `fk_salida_noconforme_empleado1_idx` (`idempleado_autoriza` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `recurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recurso` ;

CREATE TABLE IF NOT EXISTS `recurso` (
  `idrecurso` INT NOT NULL AUTO_INCREMENT,
  `recurso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrecurso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `monto_faltante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monto_faltante` ;

CREATE TABLE IF NOT EXISTS `monto_faltante` (
  `idmonto_faltante` INT NOT NULL AUTO_INCREMENT,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `fecha` DATE NOT NULL,
  `idempleado` INT NOT NULL,
  PRIMARY KEY (`idmonto_faltante`),
  INDEX `fk_monto_faltante_Empleado1_idx` (`idempleado` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `recurso_despachador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recurso_despachador` ;

CREATE TABLE IF NOT EXISTS `recurso_despachador` (
  `idrecurso_despachador` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `idempleado` INT NOT NULL,
  `idrecurso` INT NOT NULL,
  `idrecurso_minimo` INT NOT NULL,
  `evaluacion` BIT NOT NULL DEFAULT 0,
  `identificador` CHAR(34) NOT NULL,
  PRIMARY KEY (`idrecurso_despachador`),
  INDEX `fk_recursos_de_despachador_empleado1_idx` (`idempleado` ASC) VISIBLE,
  INDEX `fk_recursos_de_despachador_lista_de_recursos1_idx` (`idrecurso` ASC) VISIBLE,
  INDEX `fk_recursos_de_despachador_puntaje_minimo1_idx` (`idrecurso_minimo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idempleado` INT NOT NULL,
  INDEX `fk_user_empleado1_idx` (`idempleado` ASC) VISIBLE,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `turno_estacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `turno_estacion` ;

CREATE TABLE IF NOT EXISTS `turno_estacion` (
  `idestacion_servicio` INT NOT NULL,
  `idturno` INT NOT NULL,
  PRIMARY KEY (`idestacion_servicio`, `idturno`),
  INDEX `fk_estacion_servicio_has_turno_turno1_idx` (`idturno` ASC) VISIBLE,
  INDEX `fk_estacion_servicio_has_turno_estacion_servicio1_idx` (`idestacion_servicio` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `acceso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acceso` ;

CREATE TABLE IF NOT EXISTS `acceso` (
  `user` VARCHAR(16) NOT NULL,
  `idpermiso` INT NOT NULL,
  PRIMARY KEY (`user`, `idpermiso`),
  INDEX `fk_user_has_permiso_permiso1_idx` (`idpermiso` ASC) VISIBLE,
  INDEX `fk_user_has_permiso_user1_idx` (`user` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
